# Generated by Django 5.2.12 on 2026-03-23 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nfl', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Injury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nfl_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('athlete_nfl_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('athlete_name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('out', 'Out'), ('questionable', 'Questionable'), ('doubtful', 'Doubtful'), ('ir', 'IR'), ('day_to_day', 'Day-to-Day'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('status_display', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('injury_type', models.CharField(blank=True, max_length=100)),
                ('injury_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='injuries', to='nfl.league')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injuries', to='nfl.team')),
            ],
            options={
                'verbose_name': 'Injury',
                'verbose_name_plural': 'Injuries',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nfl_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('headline', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('story', models.TextField(blank=True)),
                ('published', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_modified', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=50)),
                ('categories', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('links', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('league', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='nfl.league')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nfl_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('description', models.TextField()),
                ('type', models.CharField(blank=True, max_length=100)),
                ('athlete_name', models.CharField(blank=True, max_length=100)),
                ('athlete_nfl_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='nfl.league')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='nfl.team')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-date', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='AthleteSeasonStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('athlete_nfl_id', models.CharField(db_index=True, max_length=50)),
                ('athlete_name', models.CharField(blank=True, max_length=100)),
                ('season_year', models.PositiveIntegerField(db_index=True)),
                ('season_type', models.PositiveSmallIntegerField(default=2)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('athlete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='season_stats', to='nfl.athlete')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='athlete_season_stats', to='nfl.league')),
            ],
            options={
                'verbose_name': 'Athlete Season Stats',
                'verbose_name_plural': 'Athlete Season Stats',
                'ordering': ['-season_year'],
                'unique_together': {('league', 'athlete_nfl_id', 'season_year', 'season_type')},
            },
        ),
    ]
